package com.nvidia.proxy;

import java.io.File;
import java.io.IOException;
import java.util.Iterator;
import java.util.Optional;
import java.util.function.Function;
import java.util.function.Supplier;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.apache.spark.connect.proto.AddArtifactsRequest;
import org.apache.spark.connect.proto.AddArtifactsResponse;
import org.apache.spark.connect.proto.AnalyzePlanRequest;
import org.apache.spark.connect.proto.AnalyzePlanResponse;
import org.apache.spark.connect.proto.ArtifactStatusesRequest;
import org.apache.spark.connect.proto.ArtifactStatusesResponse;
import org.apache.spark.connect.proto.ConfigRequest;
import org.apache.spark.connect.proto.ConfigResponse;
import org.apache.spark.connect.proto.ExecutePlanRequest;
import org.apache.spark.connect.proto.ExecutePlanResponse;
import org.apache.spark.connect.proto.FetchErrorDetailsRequest;
import org.apache.spark.connect.proto.FetchErrorDetailsResponse;
import org.apache.spark.connect.proto.InterruptRequest;
import org.apache.spark.connect.proto.InterruptResponse;
import org.apache.spark.connect.proto.ReattachExecuteRequest;
import org.apache.spark.connect.proto.ReleaseExecuteRequest;
import org.apache.spark.connect.proto.ReleaseExecuteResponse;
import org.apache.spark.connect.proto.ReleaseSessionRequest;
import org.apache.spark.connect.proto.ReleaseSessionResponse;
import org.apache.spark.connect.proto.SparkConnectServiceGrpc;
import org.sparkproject.connect.grpc.Context;
import org.sparkproject.connect.grpc.Contexts;
import org.sparkproject.connect.grpc.Metadata;
import org.sparkproject.connect.grpc.Server;
import org.sparkproject.connect.grpc.ServerBuilder;
import org.sparkproject.connect.grpc.ServerCall;
import org.sparkproject.connect.grpc.ServerCallHandler;
import org.sparkproject.connect.grpc.ServerInterceptor;
import org.sparkproject.connect.grpc.ServerInterceptors;
import org.sparkproject.connect.grpc.Status;
import org.sparkproject.connect.grpc.stub.StreamObserver;

public class GrpcGateway {
    private static final Logger LOG = Logger.getLogger(GrpcGateway.class.getName());

    private static final Context.Key<String> UNIQ_ID_CONTEXT_KEY = Context.key("uniq_id");
    private static final Metadata.Key<String> UNIQ_ID_METADATA_KEY =
            Metadata.Key.of("uniq_id", Metadata.ASCII_STRING_MARSHALLER);

    private final SessionManager sessionManager;
    private final Router router;

    public GrpcGateway() {
        sessionManager = new SessionManager();
        router = new Router();
        LOG.setLevel(Level.FINE);
    }

    /**
     * Holds common request context information extracted from gRPC requests.
     * This record encapsulates all the information needed to process a request
     * and route it to the appropriate upstream Spark Connect server.
     *
     * <p>The context is created at the beginning of each API call and passed
     * through the request processing pipeline.</p>
     *
     * @param sessionId                        The client-side session ID from the incoming request.
     *                                         This is generated by the Spark Connect client.
     * @param uniqId                           The unique identifier extracted from gRPC metadata headers.
     *                                         Used for routing requests to the appropriate upstream server.
     * @param userId                           The user ID from the request's UserContext.
     *                                         Identifies who is making the request.
     * @param service                          The upstream Spark Connect service stub determined by the router.
     *                                         All API calls will be forwarded to this service.
     * @param clientObservedServerSideSessionId The previously observed server-side session ID for this client session.
     *                                         If present, it will be set on outgoing requests to maintain
     *                                         session consistency with the upstream server.
     *                                         Empty if this is the first request for the session.
     */
    private record RequestContext(
            String sessionId,
            String uniqId,
            String userId,
            SparkConnectServiceGrpc.SparkConnectServiceBlockingStub service,
            Optional<String> clientObservedServerSideSessionId
    ) {}

    /**
     * Creates a RequestContext from common request fields.
     *
     * <p>This method performs the following steps to build the context:</p>
     * <ol>
     *   <li>Extracts the unique ID from the gRPC context (set by the auth interceptor)</li>
     *   <li>Determines which upstream Spark Connect server should handle this request
     *       based on uniqId, userId, and sessionId</li>
     *   <li>Looks up any previously observed server-side session ID for this client session,
     *       which will be used to maintain session consistency with the upstream server</li>
     * </ol>
     *
     * @param sessionId The client-side session ID from the incoming gRPC request
     * @param userId    The user ID from the request's UserContext
     * @return A fully populated RequestContext containing all information needed
     *         to route and process the request
     */
    private RequestContext createRequestContext(String sessionId, String userId) {
        // Step 1: Extract unique ID from gRPC context (set by auth interceptor)
        String uniqId = UNIQ_ID_CONTEXT_KEY.get();

        // Step 2: Determine which upstream server should handle this request
        var service = router.determineService(uniqId, userId, sessionId);

        // Step 3: Look up previously observed server-side session ID for session consistency
        Optional<String> clientObservedServerSideSessionId = sessionManager.getServerSideSessionId(sessionId, service);

        return new RequestContext(sessionId, uniqId, userId, service, clientObservedServerSideSessionId);
    }

    /**
     * Resolves and stores the serverSideSessionId, returning the consistent session ID.
     *
     * <p>This method ensures that the same client session always receives the same
     * server-side session ID, even if the upstream server returns different IDs
     * across multiple requests. This is important for session consistency in a
     * proxy environment where the client expects a stable session identifier.</p>
     *
     * <p>The resolution process:</p>
     * <ol>
     *   <li>Store the mapping between client session ID and server session ID
     *       (the first stored value wins for consistency)</li>
     *   <li>Retrieve the consistent session ID from the session manager</li>
     * </ol>
     *
     * @param clientSessionId     The client-side session ID from the original request
     * @param serverSideSessionId The server-side session ID returned by the upstream server
     * @param service             The upstream Spark Connect service that returned the response
     * @param methodName          The API method name
     * @return The consistent session ID that should be returned to the client.
     *         This may differ from serverSideSessionId if a different ID was
     *         previously stored for this client session.
     */
    private String resolveSessionId(String clientSessionId, String serverSideSessionId,
                                    SparkConnectServiceGrpc.SparkConnectServiceBlockingStub service,
                                    String methodName) {
        // Store the session ID mapping (first stored value wins for consistency)
        sessionManager.storeSessionIds(clientSessionId, serverSideSessionId, service);

        // Retrieve the consistent session ID (may be different from serverSideSessionId)
        String consistentSessionId = sessionManager.getServerSideSessionId(clientSessionId, serverSideSessionId);

        if (LOG.isLoggable(Level.FINE)) {
            LOG.fine(String.format("[%s] Session ID resolved: clientSessionId=%s, serverSideSessionId=%s, consistentSessionId=%s",
                    methodName, clientSessionId, serverSideSessionId, consistentSessionId));
        }

        return consistentSessionId;
    }

    /**
     * Executes a unary gRPC call with common session ID handling.
     *
     * @param ctx              The request context
     * @param methodName       The API method name
     * @param serviceCall      Supplier that makes the actual service call
     * @param getSessionId     Function to extract serverSideSessionId from response
     * @param updateResponse   Function to update response with consistent session ID
     * @param responseObserver The gRPC response observer
     */
    private <T> void executeUnaryCall(
            RequestContext ctx,
            String methodName,
            Supplier<T> serviceCall,
            Function<T, String> getSessionId,
            java.util.function.BiFunction<T, String, T> updateResponse,
            StreamObserver<T> responseObserver) {

        LOG.info(String.format("[%s] Request: uniqId=%s, sessionId=%s, service=%s",
                methodName, ctx.uniqId(), ctx.sessionId(), ctx.service().getChannel().authority()));

        try {
            T response = serviceCall.get();
            String serverSideSessionId = getSessionId.apply(response);
            String consistentSessionId = resolveSessionId(ctx.sessionId(), serverSideSessionId, ctx.service(), methodName);
            response = updateResponse.apply(response, consistentSessionId);

            if (LOG.isLoggable(Level.FINE)) {
                LOG.fine(String.format("[%s] Response sent: sessionId=%s", methodName, ctx.sessionId()));
            }
            responseObserver.onNext(response);
            responseObserver.onCompleted();
        } catch (Exception e) {
            LOG.log(Level.SEVERE, String.format("[%s] Error: sessionId=%s", methodName, ctx.sessionId()), e);
            responseObserver.onError(e);
        }
    }

    /**
     * Executes a streaming gRPC call with common session ID handling.
     *
     * <p>This method handles streaming API calls (like ExecutePlan and ReattachExecute)
     * where the upstream server returns multiple response messages. It ensures that
     * all responses in the stream use the same consistent server-side session ID.</p>
     *
     * <p>The streaming call flow:</p>
     * <ol>
     *   <li>Execute the upstream service call to obtain a response iterator</li>
     *   <li>For the first response, resolve and store the server-side session ID</li>
     *   <li>For all responses (including first), update with the consistent session ID</li>
     *   <li>Stream each updated response back to the client</li>
     *   <li>Signal completion when all responses have been sent</li>
     *   <li>If any error occurs, propagate it to the client via onError</li>
     * </ol>
     *
     * <p><b>Important:</b> The session ID is resolved only from the first response
     * and reused for all subsequent responses. This ensures the client sees a
     * consistent session ID throughout the entire streaming response.</p>
     *
     * @param ctx              The request context containing routing and session information
     * @param methodName       The API method name
     * @param serviceCall      Supplier that executes the upstream call and returns a response iterator
     * @param responseObserver The gRPC StreamObserver for sending responses back to the client
     */
    private void executeStreamingCall(
            RequestContext ctx,
            String methodName,
            Supplier<Iterator<ExecutePlanResponse>> serviceCall,
            StreamObserver<ExecutePlanResponse> responseObserver) {

        LOG.info(String.format("[%s] Streaming request: uniqId=%s, sessionId=%s, service=%s",
                methodName, ctx.uniqId(), ctx.sessionId(), ctx.service().getChannel().authority()));

        try {
            // Execute upstream service call to get the response iterator
            Iterator<ExecutePlanResponse> responses = serviceCall.get();

            // Track consistent session ID (resolved from first response only)
            String consistentSessionId = null;
            int responseCount = 0;

            // Stream each response back to the client
            while (responses.hasNext()) {
                ExecutePlanResponse response = responses.next();
                responseCount++;

                // Resolve session ID from the first response only
                if (consistentSessionId == null) {
                    consistentSessionId = resolveSessionId(
                            ctx.sessionId(), response.getServerSideSessionId(), ctx.service(), methodName);
                }

                // Update response with consistent session ID and send to client
                response = response.toBuilder().setServerSideSessionId(consistentSessionId).build();
                if (LOG.isLoggable(Level.FINE)) {
                    LOG.fine(String.format("[%s] Streaming response #%d: sessionId=%s",
                            methodName, responseCount, ctx.sessionId()));
                }
                responseObserver.onNext(response);
            }

            LOG.info(String.format("[%s] Streaming completed: sessionId=%s, totalResponses=%d",
                    methodName, ctx.sessionId(), responseCount));
            responseObserver.onCompleted();
        } catch (Exception e) {
            LOG.log(Level.SEVERE, String.format("[%s] Streaming error: sessionId=%s", methodName, ctx.sessionId()), e);
            responseObserver.onError(e);
        }
    }

    private class ProxyService extends SparkConnectServiceGrpc.SparkConnectServiceImplBase {

        @Override
        public void executePlan(ExecutePlanRequest request, StreamObserver<ExecutePlanResponse> responseObserver) {
            var ctx = createRequestContext(request.getSessionId(), request.getUserContext().getUserId());

            // Set clientObservedServerSideSessionId on request
            var builder = request.toBuilder();
            ctx.clientObservedServerSideSessionId().ifPresentOrElse(
                    builder::setClientObservedServerSideSessionId,
                    builder::clearClientObservedServerSideSessionId
            );
            final var finalRequest = builder.build();

            executeStreamingCall(ctx, "ExecutePlan",
                    () -> ctx.service().executePlan(finalRequest),
                    responseObserver);
        }

        @Override
        public void releaseSession(ReleaseSessionRequest request, StreamObserver<ReleaseSessionResponse> responseObserver) {
            var ctx = createRequestContext(request.getSessionId(), request.getUserContext().getUserId());
            router.releaseSession(ctx.uniqId(), ctx.userId(), ctx.sessionId());

            executeUnaryCall(ctx, "ReleaseSession",
                    () -> ctx.service().releaseSession(request),
                    ReleaseSessionResponse::getServerSideSessionId,
                    (resp, sessionId) -> resp.toBuilder().setServerSideSessionId(sessionId).build(),
                    responseObserver);
        }


        @Override
        public void analyzePlan(AnalyzePlanRequest request, StreamObserver<AnalyzePlanResponse> responseObserver) {
            var ctx = createRequestContext(request.getSessionId(), request.getUserContext().getUserId());

            // Set clientObservedServerSideSessionId on request
            var builder = request.toBuilder();
            ctx.clientObservedServerSideSessionId().ifPresentOrElse(
                    builder::setClientObservedServerSideSessionId,
                    builder::clearClientObservedServerSideSessionId
            );
            final var finalRequest = builder.build();

            executeUnaryCall(ctx, "AnalyzePlan",
                    () -> ctx.service().analyzePlan(finalRequest),
                    AnalyzePlanResponse::getServerSideSessionId,
                    (resp, sessionId) -> resp.toBuilder().setServerSideSessionId(sessionId).build(),
                    responseObserver);
        }

        @Override
        public void config(ConfigRequest request, StreamObserver<ConfigResponse> responseObserver) {
            var ctx = createRequestContext(request.getSessionId(), request.getUserContext().getUserId());

            var builder = request.toBuilder();
            ctx.clientObservedServerSideSessionId().ifPresentOrElse(
                    builder::setClientObservedServerSideSessionId,
                    builder::clearClientObservedServerSideSessionId
            );
            final var finalRequest = builder.build();

            executeUnaryCall(ctx, "Config",
                    () -> ctx.service().config(finalRequest),
                    ConfigResponse::getServerSideSessionId,
                    (resp, sessionId) -> resp.toBuilder().setServerSideSessionId(sessionId).build(),
                    responseObserver);
        }

        @Override
        public StreamObserver<AddArtifactsRequest> addArtifacts(StreamObserver<AddArtifactsResponse> responseObserver) {
            return super.addArtifacts(responseObserver);
        }

        @Override
        public void artifactStatus(ArtifactStatusesRequest request, StreamObserver<ArtifactStatusesResponse> responseObserver) {
            var sessionId = request.getSessionId();
            var uniqId = UNIQ_ID_CONTEXT_KEY.get();
            var userId = request.getUserContext().getUserId();
            var service = router.determineService(uniqId, userId, sessionId);
            LOG.info(String.format("[ArtifactStatus] Request: uniqId=%s, sessionId=%s, service=%s",
                    uniqId, sessionId, service.getChannel().authority()));
            super.artifactStatus(request, responseObserver);
        }

        @Override
        public void interrupt(InterruptRequest request, StreamObserver<InterruptResponse> responseObserver) {
            var ctx = createRequestContext(request.getSessionId(), request.getUserContext().getUserId());

            var builder = request.toBuilder();
            ctx.clientObservedServerSideSessionId().ifPresentOrElse(
                    builder::setClientObservedServerSideSessionId,
                    builder::clearClientObservedServerSideSessionId
            );
            final var finalRequest = builder.build();

            executeUnaryCall(ctx, "Interrupt",
                    () -> ctx.service().interrupt(finalRequest),
                    InterruptResponse::getServerSideSessionId,
                    (resp, sessionId) -> resp.toBuilder().setServerSideSessionId(sessionId).build(),
                    responseObserver);
        }

        @Override
        public void reattachExecute(ReattachExecuteRequest request, StreamObserver<ExecutePlanResponse> responseObserver) {
            var ctx = createRequestContext(request.getSessionId(), request.getUserContext().getUserId());

            // Set clientObservedServerSideSessionId on request
            var builder = request.toBuilder();
            ctx.clientObservedServerSideSessionId().ifPresentOrElse(
                    builder::setClientObservedServerSideSessionId,
                    builder::clearClientObservedServerSideSessionId
            );
            final var finalRequest = builder.build();

            executeStreamingCall(ctx, "ReattachExecute",
                    () -> ctx.service().reattachExecute(finalRequest),
                    responseObserver);
        }

        @Override
        public void releaseExecute(ReleaseExecuteRequest request, StreamObserver<ReleaseExecuteResponse> responseObserver) {
            var ctx = createRequestContext(request.getSessionId(), request.getUserContext().getUserId());

            var builder = request.toBuilder();
            ctx.clientObservedServerSideSessionId().ifPresentOrElse(
                    builder::setClientObservedServerSideSessionId,
                    builder::clearClientObservedServerSideSessionId
            );
            final var finalRequest = builder.build();

            executeUnaryCall(ctx, "ReleaseExecute",
                    () -> ctx.service().releaseExecute(finalRequest),
                    ReleaseExecuteResponse::getServerSideSessionId,
                    (resp, sessionId) -> resp.toBuilder().setServerSideSessionId(sessionId).build(),
                    responseObserver);
        }

        @Override
        public void fetchErrorDetails(FetchErrorDetailsRequest request, StreamObserver<FetchErrorDetailsResponse> responseObserver) {
            var ctx = createRequestContext(request.getSessionId(), request.getUserContext().getUserId());

            var builder = request.toBuilder();
            ctx.clientObservedServerSideSessionId().ifPresentOrElse(
                    builder::setClientObservedServerSideSessionId,
                    builder::clearClientObservedServerSideSessionId
            );
            final var finalRequest = builder.build();

            executeUnaryCall(ctx, "FetchErrorDetails",
                    () -> ctx.service().fetchErrorDetails(finalRequest),
                    FetchErrorDetailsResponse::getServerSideSessionId,
                    (resp, sessionId) -> resp.toBuilder().setServerSideSessionId(sessionId).build(),
                    responseObserver);
        }
    }

    private ServerInterceptor getAuthInterceptor() {
        return new ServerInterceptor() {
            @Override
            public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
                    ServerCall<ReqT, RespT> call, Metadata headers, ServerCallHandler<ReqT, RespT> next) {

                String token = headers.get(Metadata.Key.of("authorization", Metadata.ASCII_STRING_MARSHALLER));

                // Simple check: Token must be "Bearer spark-secret-token"
                if (token == null || !token.equals("Bearer spark-secret-token")) {
                    call.close(Status.UNAUTHENTICATED.withDescription("Invalid Token"), headers);
                    return new ServerCall.Listener<ReqT>() {
                    };
                }

                String uniqId = headers.get(UNIQ_ID_METADATA_KEY);  // Extract uniq_id

                if (Optional.ofNullable(uniqId).isEmpty() || uniqId.trim().isEmpty()) {
                    call.close(Status.INVALID_ARGUMENT.withDescription("Invalid uniq_id"), headers);
                    return new ServerCall.Listener<ReqT>() {
                    };
                }
                // Create new context with uniq_id attached
                Context context = Context.current()
                        .withValue(UNIQ_ID_CONTEXT_KEY, Optional.ofNullable(uniqId).orElse(""));

                return Contexts.interceptCall(context, call, headers, next);
            }
        };
    }

    public void start() throws IOException, InterruptedException {
        File certChain = new File("/opt/spark/certs/server.crt");
        File privateKey = new File("/opt/spark/certs/server.key");

        Server server = ServerBuilder.forPort(15002)
                .addService(ServerInterceptors.intercept(new ProxyService(), getAuthInterceptor()))
                .useTransportSecurity(certChain, privateKey)
                .build()
                .start();
        LOG.info("GrpcGateway proxy server started on port 15002");
        server.awaitTermination();
    }

    public static void main(String[] args) throws IOException, InterruptedException {
        Logger proxyLogger = Logger.getLogger("com.nvidia.proxy");
        proxyLogger.setLevel(Level.FINE);

        // Also set console handler to show FINE level
        for (Handler handler : Logger.getLogger("").getHandlers()) {
            handler.setLevel(Level.FINE);
        }
        new GrpcGateway().start();
    }

}
